### ISSUE TITLE
Launcher script doesn't allow passing JVM flags on command line

### ISSUE THREAD

**Issue by chaoren** [bazelbuild/rules_scala#198]
The [launcher script for scala_binary](https://github.com/bazelbuild/rules_scala/blob/2d49d201b1756cb06bf188ecc8d3e2275556f6ce/scala/scala.bzl#L304) is pretty simple. There is no way to pass JVM flags via invocation, so it's difficult for an IDE to launch the binary with a debug port and attach to it.

See the (pretty complicated) [Java launcher script](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/rules/java/java_stub_template.txt) for reference. It has flags to launch the binary for debugging and arbitrary JVM flags on the command line.

**Comment by johnynek** [comment]
yeah, that's an issue. JVM flags have to be passed in by the build.

Would welcome a PR to improve this.

**Comment by chaoren** [comment]
We could probably just borrow the Java launcher script directly. Are you okay with that?

**Comment by johnynek** [comment]
If it supports everything, yes, but since the skylark and java
implementation may be different, it is not clear that the runfiles are set
up the same.

**Comment by sdtwigg** [comment]
That sounds in line with what I almost did. #171 which rewrote it to what it mostly looks like currently drew heavily from the java launcher to do stuff like find the runfiles properly. At that time, I considered just using the java script; however, I didn't want to flatout copy it (since it had a lot of stuff, potentially under flux like handling OSX and Windows, using specialized JVM with binary files linked in, etc.). Also, wasn't (and still) unsure how to just 'depend' on that script without copying it to rules_scala.

There is one difference that emerged during review of #171 then regarding the scala_repl needing to save/restore stty settings. Would want to ensure the run_before_binary and run_after_binary stuff isn't lost in the transition.
