### ISSUE TITLE
how to provide user defined jvm_args on the command line

### ISSUE THREAD

**Issue by softprops** [bazelbuild/rules_scala#205]
It's unclear if and how to provide user provided jvm_args from the command line.

I'm not sure how this is supposed to work or it is supported but I'd like to somehow be able to do the following

```
bazel run //pkg:target -Dfoo=bar
```

bazel defines `--jvmopt=<a string>` but I don't think its intended for system properties

an attr exists for `jvm_args` but how should that work for user provided values?

**Comment by sdtwigg** [comment]
This should be fixed with #202. Note that, I'm not sure if flags setup with --jvmopt (which would work on launched java_binary) will transit to scala_binary (yet) since that may require further rules stitching.

If you are using blaze run, you can supply args to the target binary (instead of bazel) by putting them after -- so
```blaze run //pkg:target --bazelarg -- --binaryarg```

The template for the wrapper can be found here: https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/rules/java/java_stub_template.txt#L19 (although rules_scala uses specifically the 0.4.5 version, it doesn't change that quickly).

So, try something like
```blaze run //pkg:target -- --jvm_flag=foo```

**Comment by softprops** [comment]
oh that's very timely! 2 days ago. I'm a bazeleer so I need to work with in bazels tooling. I'll try updating and your suggestions

**Comment by softprops** [comment]
worked like a charm. thank you very much @sdtwigg!

**Comment by ittaiz** [comment]
A related SO question with it's answer for passing args to tests from command line (https://stackoverflow.com/questions/44571338/bazel-can-i-pass-system-property-to-test-jvm-skylark-rule/44589942?noredirect=1#comment76174371_44589942)
