### ISSUE TITLE
null entry in testlog xml

### ISSUE THREAD

**Issue by chaoren** [bazelbuild/rules_scala#231]
May cause problems with parsers.

E.g., the first entry here:
```
<?xml version='1.0' encoding='UTF-8'?>
<testsuites>
  <testsuite name='null' timestamp='1970-04-19T02:06:01.847Z' hostname='localhost' tests='3' failures='0' errors='0' time='0.284' package='' id='0'>
    <properties />
    <system-out />
    <system-err />
  </testsuite>
  <testsuite name='com.example.SomeJunit2Test' timestamp='1970-04-19T02:06:01.847Z' hostname='localhost' tests='1' failures='0' errors='0' time='0.004' package='' id='1'>
    <properties />
    <testcase name='passingTest2' classname='com.example.SomeJunit2Test' time='0.004' />
    <system-out />
    <system-err />
  </testsuite>
  <testsuite name='com.example.SomeJunitTest' timestamp='1970-04-19T02:06:01.851Z' hostname='localhost' tests='1' failures='0' errors='0' time='0.0' package='' id='2'>
    <properties />
    <testcase name='passingTest' classname='com.example.SomeJunitTest' time='0.0' />
    <system-out />
    <system-err />
  </testsuite>
  <testsuite name='SomeSpecs2Test' timestamp='1970-04-19T02:06:02.131Z' hostname='localhost' tests='1' failures='0' errors='0' time='0.0' package='' id='3'>
    <properties />
    <system-out />
    <system-err />
  </testsuite>
  <testsuite name='example test should' timestamp='1970-04-19T02:06:02.131Z' hostname='localhost' tests='1' failures='0' errors='0' time='0.0' package='' id='4'>
    <properties />
    <testcase name='example test should::allow to pick only me' classname='com.example.SomeSpecs2Test' time='0.0' />
    <system-out />
    <system-err />
  </testsuite>
</testsuites>
```

**Comment by chaoren** [comment]
From this project: https://github.com/ittaiz/bazel-scala-getting-started

**Comment by ittaiz** [comment]
cc @hmemcpy

**Comment by hmemcpy** [comment]
Alright. After some extensive digging, I finally understand what's going on here, and how to (possibly) fix it.

Our [`Specs2PrefixSuffixTestDiscoveringSuite`](https://github.com/bazelbuild/rules_scala/blob/master/src/java/io/bazel/rulesscala/specs2/Specs2RunnerBuilder.scala) is a "parent" runner, which aggregates child runners under it. In practical terms, in runtime, it looks like this:

    Specs2PrefixSuffixTestDiscoveringSuite::getChildren
    +--  Runner for SomeJunitTest
    +--  Runner for SomeJunit2Test
    +--  Runner for SomeSpecs2Test
    ...

Now, bazel's `JUnit4TestModelBuilder` [asks for a root `Description`](https://github.com/bazelbuild/bazel/blob/5655c7fab3a5cdcd149db66d00a9ccda3702de59/src/java_tools/junitrunner/java/com/google/testing/junit/runner/junit4/JUnit4TestModelBuilder.java#L48-L55) from the current runner. In case of specs2, the Runner will be our `Specs2PrefixSuffixTestDiscoveringSuite`, and the call to `getDescription` will return some composite Description, whose `displayName` is "null", and whose children are the top-level descriptions for each one of the test suites, i.e.:

    Description(null)
    +-- Description(SomeJunitTest)
           +-- ...
    +-- Description(SomeJunit2Test)
           +-- ...
    +-- Description(SomeSpecs2Test)

With the `null` description becoming the `root` node. The loop that builds the model in bazel will have added the `root` node after adding all the children, which causes this null case to be added to the model.

I see two possible fixes here:
1. Override `Specs2PrefixSuffixTestDiscoveringSuite::getDescription` and build a composite `Description` node manually, giving it some name. test.xml will display the name instead of null, but otherwise remain unchanged. This is fixed entirely in `rules_scala`.
2. Fix the model building part to always extract the "children" from the composite root node (only in cases of scala/specs2), and pass the children as top-level nodes to the model builder. It already supports this functionality. This will remove the bad "root" node, as well as fixing an unneeded layer in junit.xml, e.g. this:

```
<?xml version='1.0' encoding='UTF-8'?>
<testsuites>
...
<testsuite name='SomeSpecs2Test' timestamp='1970-04-19T02:06:02.131Z' hostname='localhost' tests='1' failures='0' errors='0' time='0.0' package='' id='3'>
    <properties />
    <system-out />
    <system-err />
</testsuite>
<testsuite name='example test should' timestamp='1970-04-19T02:06:02.131Z' hostname='localhost' tests='1' failures='0' errors='0' time='0.0' package='' id='4'>
    <properties />
    <testcase name='example test should::allow to pick only me' classname='com.example.SomeSpecs2Test' time='0.0' />
    <system-out />
    <system-err />
</testsuite>
</testsuites>
```

into:
```
<?xml version='1.0' encoding='UTF-8'?>
<testsuites>
...
<testsuite name='example test should' timestamp='1970-04-19T02:06:02.131Z' hostname='localhost' tests='1' failures='0' errors='0' time='0.0' package='' id='4'>
    <properties />
    <testcase name='example test should::allow to pick only me' classname='com.example.SomeSpecs2Test' time='0.0' />
    <system-out />
    <system-err />
</testsuite>
</testsuites>
```

Which is a more readable version overall.

This will require a small change in `bazel` to flatten the root node, as well as (probably) changes in the intellij plugin (and other tools) that read bazel's junit.xml

The third option is to add a check for the null case and manually prevent it from being added to the model/xml. This is also a fix in bazel, and will probably need a comment, explaining that it is scala/specs2 specific.

**Comment by ittaiz** [comment]
Awesome!
Re 1- we can just return a hard coded name like “Aggregation of all
relevant test classes”, right?
Re 2- I think that if all tools which process this xml will need to change
then this might be a problem.

Wdyt?
