### ISSUE TITLE
strict deps is undocumented in the readme

### ISSUE THREAD

**Issue by johnynek** [bazelbuild/rules_scala#283]
I think the strict deps work is in now? @ittaiz is that right?

If so, it is not clear to me what I am supposed to do to use it. Could we add some explanation of how to do that to the README?

**Comment by ittaiz** [comment]
it's a bit by design.
I was actually waiting for 0.6.0 (fresh out of the oven today) for a couple
of very basic stuff (one being the ability to use warn from command line).
Let me try and play with my branch with 0.6.0 and see if it passes or needs
yet more things which are on HEAD.
If you don't need any java interop then it works.
The reason I still want it to be with a feature toggle, off by default and
undocumented is because we're trying to asses the performance impact of
this.
This is my main focus for some time now so there's no worry it will just
stay as is

**Comment by johnynek** [comment]
With some docs, we could give you some feedback in another use case! :)
