### ISSUE TITLE
scala_version info/change documentation

### ISSUE THREAD

**Issue by schmitch** [bazelbuild/rules_scala#349]
Hello is there any way to output on which scala_version somebody is?
I mean currently I have no idea on which scala version I might compile the project.

also I have no idea how to flip the scala version. currently this behavior could be documented.

**Comment by ittaiz** [comment]
Not really. If you load the scala_repositories method then you use whatever
is defined there (2.11.8?).
If you define your own then it's defined there.
If you want to use 2.12.x then there is currently a branch to enable this.
We have a couple of open issues about this.
It's not documented since it's not really clear.

Can you expand what you mean about the java version?

**Comment by schmitch** [comment]
I had a typo (meant scala version), well I didn't knew that it currently only supports scala 2.11.
well too bad, but still thanks for the information. I hope there is a way to switch version at some point.

**Comment by ittaiz** [comment]
Again, it's not correct that it only supports scala 2.11.
@gkk-stripe from Stripe has started using it with 2.12 in the branch I mentioned and Wix will start using this branch in a few weeks as the only branch it uses.
I agree it's a shame the switch isn't cleaner but that's where we are.
If you want to contribute to making it more generic we'd love the help
