### ISSUE TITLE
custom generators for scala proto

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/rules_scala#352]
We (at Wix) have a need for a custom scala proto generator.
As so it happens we have a custom generates that extends scalapb but that doesn't mean it will always be like it.
Are there objections to extracting a more "low-level" rule out of the existing scalapb prot library which maybe will be called `scala_proto_library` and that accepts custom generators?
There is an option this will default to scalapb if no arg is given but I'm not sure if it's a good idea, should probably be discussed.
@azymnis WDYT?

cc @johnynek @simuons  @vipo

**Comment by johnynek** [comment]
I'm open to it, but i am worried it adds complexity. It would be nice to make it work by default, but also easy to share as much as possible.

**Comment by azymnis** [comment]
I'm open to it too and not particularly wed to scalapb. I think the main issue is that most of the rule code is around massaging the input params to a format that scalapb accepts, and parsing flags. If you could specify a different executable instead of scalapb, that could probably work too, as long as it accepts the same command line flags
