### ISSUE TITLE
scala_import mixes ijars into the runtime classpath

### ISSUE THREAD

**Issue by johnynek** [bazelbuild/rules_scala#354]
@gkk-stripe may follow up more but we saw an issue with scala_import preventing us from using it.

The issue seems to be pretty easy to fix (sorry I’m on the phone and can’t easily link). There is a spot where you explicitly put a compile jar onto the runtime path. This can break. Since compile jars may be ijars and they don’t have code sections.

We didn’t see all the ijars on the runtime path, only a subset and we didn’t guess right away which they were.

**Comment by gkossakowski** [comment]
Yeah, we ran into an issue with scala_import causing ijars to appear on runtime path. I was busy with other things and didn't get around to reporting it. I have a minimal repro + fix. Will post later.

**Comment by ittaiz** [comment]
I'm looking at the code paths and I saw the line you're referring to but I
think the question might be of intended usage.
scala_import for now doesn't utilize ijar at all and is awaiting a revamp
in java_provider to make these bits easier.
The above can happen if:
1. the `jars` you're giving to scala_import are already ijars. I'd say that
this isn't the API I want since I want people to give raw jars and signal
via an attribute (which I'll add) if they want ijars there or not (due to
macros). In any case this needs to be documented.
2. exports- I think this might happen with exports as well and it's just a
bug.

If it's only #2 I have a fix (though not sure which test will reproduce it
exactly)

**Comment by gkossakowski** [comment]
It's 2. and I have a repro. Ok, let me post this right away in on cleaned up way.

**Comment by ittaiz** [comment]
Sure thing.
Waiting for it :)

**Comment by gkossakowski** [comment]
Repro (that breaks `build test`) + what appears to be a fix.

```patch

commit 2b1161951b09a9e277efe3f40d61bbd02e558e20
Author: Grzegorz Kossakowski <gkk@stripe.com>
Date:   Fri Dec 1 22:28:23 2017 -0800

    Book progress on scala_import depending on java_import

diff --git a/scala/scala_import.bzl b/scala/scala_import.bzl
index 49d9a8d..ad369ba 100644
--- a/scala/scala_import.bzl
+++ b/scala/scala_import.bzl
@@ -95,7 +95,7 @@ def _collect_exports(exports):

   for dep_target in exports:
       java_provider = dep_target[java_common.provider]
-      exported_jars += java_provider.compile_jars
+      exported_jars += java_provider.full_compile_jars

   return exported_jars

diff --git a/test/src/main/scala/scala/test/scala_import/BUILD b/test/src/main/scala/scala/test/scala_import/BUILD
index 3744c80..7262697 100644
--- a/test/src/main/scala/scala/test/scala_import/BUILD
+++ b/test/src/main/scala/scala/test/scala_import/BUILD
@@ -49,10 +49,15 @@ scala_specs2_junit_test(
     suffixes = ["Test"],
 )

+java_import(
+  name = "guava_and_commons_lang_java_import",
+  jars = ["@com_google_guava_guava_21_0//jar:file", "@org_apache_commons_commons_lang_3_5//jar:file"],
+)
+
 #Exports
 scala_import(
   name = "guava_and_commons_lang_as_exports",
-  exports = [":guava_and_commons_lang"],
+  exports = [":guava_and_commons_lang_java_import"],
 )
```

**Comment by gkossakowski** [comment]
I hestiated to post this earlier because I thought it's breaking intellij plugin but I think i had something wonky with my caches. A clean build + import in the intellij made it to work.

**Comment by ittaiz** [comment]
Looks good! Exactly the fix I had in mind.
Can also remove the `if` at https://github.com/bazelbuild/rules_scala/blob/master/scala/scala_import.bzl#L24? that would be great. The `if` was there to be backward compatible with older versions of bazel (pre 0.7.0 I think) and since we're now counting on this `full_compile_jars` api then we can drop this ugly `if`.

**Comment by gkossakowski** [comment]
Thanks, yes! Will post a PR. A tangent, why don't we generate `source_jar` info?

**Comment by ittaiz** [comment]
No reason other than time.
See this comment (
https://github.com/bazelbuild/rules_scala/pull/326#issuecomment-345540587)
on stuff we need to add. It's number 4 IINM.
It's not 100% clear to me on how match the right source jar to the bytecode
jar if we get a few of them other than ugly string manipulation but I guess
that's solvable

**Comment by ittaiz** [comment]
@gkossakowski Sorry but come to think of it the above diff is actually less than optimal since it will make depending on the full jars of the exports for compilation.
Another fix which should be very similar is to pass the `exports` and the `current_jars` separately to `_create_provider` and only add the `current_jars` to the transitive part.
That should work since the `exports` are already included in the other transitive sets.
Wait, actually I think the `exports support is actually faulty. IINM the current implementation doesn't propagate its transitive dependencies... :(
@iirina don't want to add more pressure but the current API just enabled me to add a host of bugs...

**Comment by gkossakowski** [comment]
Is using full jars for exports of `scala_import` a problem? Using full jars is problematic for incremental compilation of downstream dependencies of a target. But `scala_import` is used for importing external dependencies that don't change within the build except when the dependency is updated. Am I overlooking something?

**Comment by ittaiz** [comment]
you are.
scala_import can export also internal targets. for us we definitely have
scala_import targets which have deps on internal targets.
Not sure about exports but it can happen

**Comment by gkossakowski** [comment]
what's the use case for using scala_import to export internal targets? I thought it's modelled after `java_import` that is described as:
> This rule allows the use of precompiled .jar files as libraries for java_library and java_binary rules.

**Comment by ittaiz** [comment]
indeed. but then you can ask what's the use case for having
deps/runtime_deps/exports at all. Additionally those rules do propagate
only the ijars to the compile classpath.
Not saying there is a clear one but it's not out of the question someone
will want to use it like this

**Comment by gkossakowski** [comment]
I think the exports section and the runtime_deps section make sense to be able to create a "bundle" of external jars. We use exports in bazel-deps to pass on transitive dependencies. The important property is that scala_import only depends (via any of the attributes) on other scala_import targets or java_import targets.
That was my understanding of the applicability of that rule.

I'm happy to submit a different patch. What would be your suggestion?

**Comment by gkossakowski** [comment]
following up on an earlier conversation, do we assume that
> if hasattr(test_provider, "full_compile_jars"):

is always true and that's why we don't need the if?

**Comment by ittaiz** [comment]
yes. because this was a way to be backward compatible with older bazel versions but your change mandates the newer version so we can drop the if
