### ISSUE TITLE
scala_import's exports doesn't propagate its dependencies

### ISSUE THREAD

**Issue by gkossakowski** [bazelbuild/rules_scala#359]
> The existing one is that exports don't propagate their dependencies.
> If you use scala_import with exports a bit like one uses maven pom as an aggregator then this might be a problem

https://github.com/bazelbuild/rules_scala/pull/357#issuecomment-349423855

**Comment by gkossakowski** [comment]
To understand better this issue, I'd like to ask about this code in scala_import impl:

```
return java_common.create_provider(
          use_ijar = False,
          compile_time_jars = current_target_compile_jars,
          transitive_compile_time_jars = jars.transitive_compile_jars + current_target_compile_jars,
          transitive_runtime_jars = transitive_runtime_jars + jars.transitive_runtime_jars + current_target_compile_jars,
      )
```

why `transitive_runtime_jars jars` attribute is getting compile_jars?

**Comment by ittaiz** [comment]
it's hard to say since the current API is very very flawed but essentially if you specify one of the transitive options then it's your responsibility to pass the current one for the transitive sets.
You can try and uncomment whatever you want and see what test breaks.
All of these are covered.
@iirina is working on a new **much** saner api
btw,
we actually tried switching to exports but it didn't work.
I also think there might be a bug with deps but haven't been able to pinpoint it yet

**Comment by ittaiz** [comment]
I have a fix, hopefully will be sent tomorrow.
https://github.com/wix/rules_scala/commit/95ebb78872b687c32a407655a3748d49007294be
BTW @gkossakowski two things that I think might not be clear in the above snippet:
current_target_compile_jars should be the jars of this current scala_import and they should be full jars so it's ok to put them in the transitive runtime jars.
see the above commit for a clearer picture
