### ISSUE TITLE
Add travis_ci tests

### ISSUE THREAD

**Issue by johnynek** [bazelbuild/rules_scala#4]
this recipe may help:

https://github.com/korfuri/bazel-travis

**Comment by johnynek** [comment]
@damienmg I don't think I can turn on travis-ci for the repo (I don't think I have rights). If you turn this on, I'll follow the above steps so we can keep the build green.

**Comment by damienmg** [comment]
Added Travis to the organization and as a service to the repository. I still miss somethings, apparently getting to see the organization authorization in Travis take some time. I will retry later today.

Travis CI is definitely a better idea for PR, you don't need the complex setup needed for Bazel. Jenkins can helps us detect failures caused by Bazel (as well as mac and soon to be windows).

(yes sorry, we cannot give you more that write access to the repo per Google policy)
